# Projet de mini-mud: Utilisation de la librairie SDL
#
# Makefile.config: Définitions globales pour les Makefiles des différents
#                  modules
#
# Objectif: Apprendre à construire un Makefile dans le cadre d'un projet
#
# Auteurs et Licence: Ce projet est un logiciel libre sous licence GNU GPL,
#                     voir les fichiers "Authors" et "License" pour les détails.
##############################################################################

$(info "  - Chargement de ./Makefile.config")
# Valeurs des définitions globales
# ================================
#
# Notes:
# Typiquement, ces valeurs seront obtenues et affectées par un outil
# de génération multi-plateforme (ex: automake et autoconf):
#  - automake: http://www.gnu.org/software/automake/manual/automake.html#Introduction
#  - autoconf: http://www.gnu.org/software/autoconf/manual/autoconf.html#Introduction
#
# Dans d'autres cas, il pourra être à renseigner par l'utilisateur, mais ce
# n'est pas la démarche conseillée.

# Identification du package
PACKAGE="mini-mud"

# Définition des chemins
# Inspiré des chemins définis par défaut pour "automake":
#    http://www.gnu.org/software/automake/manual/automake.html#Standard-Directory-Variables
prefix=/home/r3vlibre
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib

includedir=${prefix}/include
datarootdir=${prefix}/share
datadir=${datarootdir}
mandir=${datarootdir}/man
infodir=${datarootdir}/info
docdir=${datarootdir}/doc/${PACKAGE}

# Identification du compilateur sur la machine cible
# Insprié des variables de configuration stanadard pour "automake":
#     http://www.gnu.org/software/automake/manual/automake.html#Standard-Configuration-Variables
CC=gcc
CFLAGS=
CXX=g++
CXXFLAGS=-g
LDFLAGS=
CPPFLAGS=
