# Projet de mini-mud: Utilisation de la librairie SDL
#
# Makefile: Compilation et installation du projet mini-mud avec la librairie SDL
#
# Objectif: Apprendre à construire un Makefile dans le cadre d'un projet
#
# Auteurs et Licence: Ce projet est un logiciel libre sous licence GNU GPL,
#                     voir les fichiers "Authors" et "License" pour les détails.

$(info echo "* Chargement de src/communication/Makefile")
## Import des règles génériques de compilation d'un module
include $(srcdir)/Makefile.common


## Règles spécifiques à la racine du code source
# Pour le répertoire principal, réinitialisation des modules identifiés
# pour le remplacer par les binaires à construire.


$(info "CC=$(CC)")
$(info "CCFLAGS=$(CCFLAGS)")
$(info "CXX=$(CXX)")
$(info "CXXFLAGS=$(CXXFLAGS)")
$(info "binaires=$(binaires)")
$(info "module=$(module)")
$(info "subdirs=$(subdirs)")
$(info "subdirs_base=$(basename $(subdirs))")
$(info "liste_modules=$(liste_modules)")
$(info "liste_objets=$(liste_objets)")

